---
stages:
  - syntax
  - unit

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

parallel_spec-Ruby 2.1.9-Puppet ~> 4.0:
  stage: syntax
  image: ruby:2.1.9
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 4.0'

check:symlinks check:git_ignore check:dot_underscore check:test_file-Ruby 2.4.4-Puppet ~> 5.5:
  stage: syntax
  image: ruby:2.4.4
  script:
    - bundle exec rake check:symlinks check:git_ignore check:dot_underscore check:test_file
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

syntax lint metadata_lint-Ruby 2.4.4-Puppet ~> 5.5:
  stage: syntax
  image: ruby:2.4.4
  script:
    - bundle exec rake syntax lint metadata_lint
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

rubocop-Ruby 2.4.4-Puppet ~> 5.5:
  stage: syntax
  image: ruby:2.4.4
  script:
    - bundle exec rake rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

parallel_spec-Ruby 2.4.4-Puppet ~> 5.5:
  stage: syntax
  image: ruby:2.4.4
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

