---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  global_env: 
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  branches:
  - release
  use_litmus: true
  litmus:
    provision_list:
      - travis_ub
      - travis_deb
      - travis_el6
      - travis_el7
  simplecov: true
  notifications:
    slack:
      secure: Wf7Wz3KC0G9ngPiDcOIpSqcCfdvwKQqZdNH/z3GMcj/OipMAdyFSAVnBvikIl7L1c0LMU9ATEpub+jYzViT7RZywaNyer6SRAfs6MIgAYo4xxF/mOnDHAxXeUYAsBXXL4sS3NX2XWMPa9ZWUeuUQKth8O4STWgAX298QZLyYx5k=
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
